version: '3'

services:
    nearby:
      build: .
      # links: 
      #   - cache
      # depends_on:
      #   - cache
      ports:
        - 3004:3004

    # cache:
    #   image: redis:latest
    #   ports:
    #     - 6379:6379